# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runner's shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runner's shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Azure Resource Manager (ARM) Template Deployment
      uses: whiteducksoftware/azure-arm-action@v3.1
      with:
        # Paste output of `az ad sp create-for-rbac -o json` as value of secret variable: AZURE_CREDENTIALS
        creds: AZURE_CREDENTIALS
        # Provide the name of a resource group.
        resourceGroupName: mrbtest
        # Specify the path to the Azure Resource Manager template.
        templateLocation: $GITHUB_WORKSPACE/ARMTemplates/template.json
        # Specifies the name of the resource group deployment to create.
        deploymentName: FirstGithubDeployment
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).
        deploymentMode: # optional, default is Incremental
        # Specify either path to the Azure Resource Manager parameters file or pass them as 'key1=value1;key2=value2;...'.
        parameters: # optional
        # Specify either path to the Azure Resource Manager override parameters file or pass them as 'key1=value1;key2=value2;...'.
        overrideParameters: # optional
